### ISSUE TITLE
Update/Fix/Add munich canteens

### ISSUE THREAD

**Issue by Martinif** [mswart/openmensa-parsers#105]
This is a issue collecting various updates for munich canteens i would propose and also implement.

- [x] Add more canteens managed by the Munich Student Union. There are currently 27 canteens but only 17 are supported by openmensa. Now we will be supporting 20/27 canteens
- [x] grosshadern: rename it and fix the broken link
- [x] test all existing canteens
- [x] rename arc**h**isstrasse #93 

Since I would be reworking the canteens, I could also fix Issue #93 here

**Comment by klemens** [comment]
This is great! Feed free to ping me if you need any help (in the meantime, I can access the canteens on openmensa.org).

**Comment by Martinif** [comment]
Thanks! I added all canteens apart from these 7:

StuBistro Benediktbeuern: png only
StuBistro Schillerstraße:  No plan online
StuCafe Heßstrasse: No plan online, "coming soon"
StuCafé Olympiapark: No plan online, "coming at the start of the semester" (this was 5 weeks ago)
StuCafé in der Mensa Weihenstephan: No plan online, Link dead
StuCafe Leopoldstraße: Different webpage, needs a modified parser: https://www.studentenwerk-muenchen.de/index.php?id=stucafe-leopoldstrasse
StuCafe Audimax: Different webpage, needs a modified parser: https://www.studentenwerk-muenchen.de/index.php?id=stucafe-audimax

I frankly do not plan to invest much time into modifying the parser in this issue. Maybe I will do it at some point in the future, but I would exclude it from this issue.

**Comment by klemens** [comment]
Fixed by #106.
