### ISSUE TITLE
Docs outdated?

### ISSUE THREAD

**Issue by Memorion** [mswart/openmensa-parsers#14]
I tried to run a parser as specified in the readme with: 
`python3 parse.py magdeburg ovgu-unten`

but I get this error:
`python3 parse.py magdeburg ovgu-unten
Traceback (most recent call last):
  File "parse.py", line 14, in <module>
    print(parse(SimulatedRequest(), *sys.argv[1:]))
  File ".../openmensa-parsers/config.py", line 15, in parse
    return parsers[parser_name].parse(request, *args)
  File ".../openmensa-parsers/utils.py", line 50, in parse
    return self.sources[source].parse(request, *args)
TypeError: parse() missing 1 required positional argument: 'feed'`

**Comment by mswart** [comment]
Yes, I refactored the parsers in the last days. As I am not yet sure how it will looks like in the future the documentation is deprecated.

`parser.py` takes takes now the following parameters:
  * `$parser index.json` list of canteens with urls for this parser
  * `$parser $canteen metadata.xml` for metadata feed v2.1 (if supported; currently only halle)
  * `$parser $canteen $feed.xml` real feed data; most canteens support today.xml and full.xml; But this is parser specific; halle has e.g. today, thisWeek and nextWeek

The parser for halle (`halle.py`) is the one that should used as example for new ones.

I try to update the documentation within the next days.

**Comment by Memorion** [comment]
I'm a little confused, does that mean that there currently is now way to locally test a parser? or you can only locally test halle?

if I try `python3 parse.py halle tulpe  metadata.xml` 
I get: 
```
/usr/local/lib/python3.4/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
<?xml version="1.0" encoding="UTF-8"?>
<openmensa version="2.1" xmlns="http://openmensa.org/open-mensa-v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://openmensa.org/open-mensa-v2 http://openmensa.org/open-mensa-v2.xsd">
  <version>1.0</version>
  <canteen>
    <name>Mensa Tulpe</name>
    <address>Universitätsring 5, 06108 Halle</address>
    <city>Halle</city>
    <phone>+49 345 5522924</phone>
    <location latitude="51.487015" longitude="11.969186"/>
    <availability>public</availability>
    <feed name="today" priority="0">
      <schedule dayOfMonth="*" dayOfWeek="*" hour="8-14" minute="0"/>
      <url>http://example.org/halle/tulpe/today.xml</url>
    </feed>
    <feed name="thisWeek" priority="1">
      <schedule dayOfMonth="*" dayOfWeek="*" hour="8" minute="0" retry="2 3600"/>
      <url>http://example.org/halle/tulpe/thisWeek.xml</url>
    </feed>
    <feed name="nextWeek" priority="2">
      <schedule dayOfMonth="*" dayOfWeek="*" hour="9" minute="0"/>
      <url>http://example.org/halle/tulpe/nextWeek.xml</url>
    </feed>
  </canteen>
</openmensa>
```
but `python3 parse.py halle tulpe today.xml`
gets me:
```
/usr/local/lib/python3.4/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
Traceback (most recent call last):
  File "parse.py", line 14, in <module>
    print(parse(SimulatedRequest(), *sys.argv[1:]))
  File "/Users/memorion/Projects/Stuff/openmensa-parsers/config.py", line 15, in parse
    return parsers[parser_name].parse(request, *args)
  File "/Users/memorion/Projects/Stuff/openmensa-parsers/utils.py", line 50, in parse
    return self.sources[source].parse(request, *args)
  File "/Users/memorion/Projects/Stuff/openmensa-parsers/utils.py", line 139, in parse
    return feed(self, request)
  File "/Users/memorion/Projects/Stuff/openmensa-parsers/halle.py", line 74, in today
    self.parse_data(day=day.day, month=day.month, year=day.year)
  File "/Users/memorion/Projects/Stuff/openmensa-parsers/halle.py", line 40, in parse_data
    category = tds[1].find('span', attrs={'class': 'npsble'}).text or 'Hauptessen'
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by mswart** [comment]
The warning is new to me. It was added in BeautifulSoup 4.4; I currently test only with bs 4.1 and mostly develop on 4.2. For halle I fixed this in eb1348b429. The other parsers come later.

One remark on that: I think as `html.parser` was not imported explicitly; bs4 always used `lxml` in my cases.

Your `AttributeError` occurs only with `html.parser`. It should therefore work now. But keep in mind, that the canteen pages are changed often. So it can be that a parser is outdated and currently not able to parse a specific parsers/canteens.

**Comment by Memorion** [comment]
Yes, it works now thanks! I wanted to know how I can locally test the parsers specifically because they can break so easily and now I can hopefully try to fix a parser in case it breaks, verify the new behaviour works and submit a PR

**Comment by mswart** [comment]
You can also take a look at `test-urls.txt`. This is a list of urls that must return a valid xml document. They are automatically checked by travis before new deployments. The url is `http://localhost:9090` append by all `parse.py`'s arguments joined by `/`.
