### ISSUE TITLE
add howto for developers of new parser

### ISSUE THREAD

**Issue by azrdev** [mswart/openmensa-parsers#2]
I built a parser similar to the ones in this repo, and using your pyopenmensa. How would I (or anyone else) continue now, send a pull request and wait? If a new parser appears here, how will its output get into the openmensa database? (Yes, that last question is not really your concern, but I didn't find any answer to it, and I suppose you did)

Might be a good idea to also write this up in the readme for anybody else :-)

**Comment by cvzi** [comment]
I  have created a python program that hopefully provides a feed for a mensa in Heidelberg.
For now I have hosted it on openshift:
http://mensahd-cuzi.rhcloud.com/today/Mensa%20Im%20Neuenheimer%20Feld%20304
and
http://mensahd-cuzi.rhcloud.com/all/Mensa%20Im%20Neuenheimer%20Feld%20304

What do I have to do next if I want to add it to openmensa?

**Comment by klemens** [comment]
I guess we can close this ticket. 😉
