### ISSUE TITLE
München & Nürnberg do not work anymore

### ISSUE THREAD

**Issue by flippinger** [mswart/openmensa-parsers#37]
all locations in München/Garching and Nürnberg/Erlangen that I tested do not work anymore.

For example:
- http://openmensa.org/c/256
- http://openmensa.org/c/138
- http://openmensa.org/c/139

API returns error 500.

**Comment by klemens** [comment]
München should work fine now with 748ee85ca465aec889acbcb28678a5fd0a4a6807.

It seems nothing is wrong with Nürnberg except that the menu was last updates at 28.09.2016? I am not sure whats the problem here.. @mswart @theScrabi

**Comment by mswart** [comment]
By df6062c0f209a8bd2436a25a25e957761cde2ae1 and 07346ce769b59a9fe493492733f46ecdfb317bf3 Nürnberg/Erlangen produce again valid XML-Feeds. Update worked fine (new weeks were imported).

**Comment by flippinger** [comment]
Thanks for the quick fix. Nice work!
