### ISSUE TITLE
Parser for Aachen seems broken

### ISSUE THREAD

**Issue by Harry-R** [mswart/openmensa-parsers#61]
Aachen changed to a new menu system, the parser seems to be broken. 

 [Link to Studierendenwerk Aachen](http://www.studierendenwerk-aachen.de/en/news/article/switch-to-a-new-menu-system.html)

[Link to openmensa website with missing menu information](https://openmensa.org/c/187)

**Comment by manorom** [comment]
#59 should fix this, just waiting for it to be merged...

**Comment by tretum** [comment]
Unfortunately there hasn't been any reaction to any of the pull requests fixing the parser, yet 😞
Considering that one request is open for nearly two weeks it would be nice to at least have some kind of response.

**Comment by Y0hy0h** [comment]
There are a lot of PRs addressing this issue: #59, #60, #62 and tangentially #63. Some of our projects depend on OpenMensa and it is discouraging to see that weeks after submitting mergable fixes, nothing has happened. Could you give us an update on the current situation and what will be done next? :)

**Comment by tretum** [comment]
Unfortunately it seems like it's time to use/host our own parsers. What a shame :(

**Comment by mswart** [comment]
Sorry for the late response. I was one long vacation during November and December celebrating my master's degree.
I have merged a PR and the feeds should now finally working again.

@tretum The core idea behind OpenMensa is distribution and the goal is one dedicated maintainer per parser who using the referring canteens regularly and can deploy fixed within short timeframes. But sadly this is currently not the case. I started with this collection to gain initial support for some large providers of canteens. But I hope to pass the maintenance off to dedicated people from Aachen. I asked the PR authors if they are interested in this task, we will see if they are interested.

For many people, it is a huge burden to deploy and host their own parser. This is one reason I (still) offer to add and host foreign parsers. Unless there is a good working alternative (like ready to use documentation how to easily run your parser one Google App Engine) will continue to do so.

I know this situation is not ideal but it is the best we can do for now.
As a mitigation, I offer write access for interested persons to allow them to keep their parser up-to-date themselves. I try to concentrate on hosting the parsers itself and finding time to maintain openmensa and pyopenmensa itself.

I am very grateful that @theScrabi, @klemens, @CooperRS use this and therefore maintain their parser without my interaction. Sometimes they even help out on other PR :+1:

Furthermore, I want to make it easier to take over the hosting and maintenance of existing canteens and parsers. But this requires further changes to OpenMensa itself and I lack time to implement these changes (there are other bug fixes and features that should have been implemented long time ago). In the end, it is still a side project I do for free in addition to studies and work. If anyone wants to help I am happy to help and guide.

**Comment by Y0hy0h** [comment]
@mswart, congrats on your master's!

I think what made us nervous was that we had no meaningful reaction whatsoever. A quick "Am on vacation, will look at this in January" would have been perfect.  
But please don't take this as being unthankful. Your project is really awesome and especially after you've just pointed it out again, I really do appreciate the work you continue to put in! It's easy to forget that servers don't run themselves. The above comment is just meant as a possible compromise if a similar situation arises again.

That criticism being made, I would be happy to work on a bigger project. I've noticed that I lack experience with bigger systems. So if you could guide me, this would be an awesome opportunity for me to learn and improve.  
Please note, though, that I cannot guarantee how much work I can put into this. But right now it seems like I could work on this every few days. :)

I am also willing to take over responsibility for the Aachener parser. It seems like taking care of only one parser is a manageable workload. ;) 

Thanks again for providing this service!

**Comment by mswart** [comment]
@Y0hy0h Thank you. I have added you to the list of collaborators. This allows you to merge PRs (and push commits). I would prefer that you stick to PR whenever possible. Feel free to comment and merge other PRs if you find time and they fix broken parsers. It is good to merge them in a timely manner: I might not be able to do that.
Only big refactorings and adjustment towards to build and deploy process should not be merged without my acknowledgement.

**Comment by Y0hy0h** [comment]
Gotcha. Will only merge parser fixes and wait for you to merge any other PR. 👍   
Thanks!

**Comment by Y0hy0h** [comment]
@mswart, just to double check: As the maintainer for the Aachener parser I can refactor them myself, right? So I could merge my PR #63 which adds a test?

**Comment by mswart** [comment]
@Y0hy0h Yes, every parser specific changes are OK. With big refactoring I mean adjustments include multiple if not all parsers.

**Comment by Y0hy0h** [comment]
Perfect, thanks for the clarification!
