### ISSUE TITLE
Lack of Feedback from Maintainer

### ISSUE THREAD

**Issue by Y0hy0h** [mswart/openmensa-parsers#80]
I just wanted to discuss the issue of the frankly slow feedback and merges from @mswart. It's difficult to stay excited and help with this project, without getting meaningful feedback and changes.

I know it sounds harsh, but I do not mean it as a personal attack. He has built all of this and continues to run everything, and I am sure everyone is very thankful for all the effort he puts into this project.  
This issue is primarily about discussing how we all can help with the fact that @mswart has other responsibilities than this project. None of us, can spend all their time on here, which makes the contributions and work from @mswart even more impressive.

Maybe there is some simple change that will help solve this issue. Could we declare a "vice-president' that has the authority to guide the project when he's inactive? Maybe @mswart can check in twice a week, without sacrificing too much time?  
I'm just throwing ideas around. What I'd like is to discuss this issue, because I truly believe that it hurts OpenMensa.

Again, @mswart is at no fault. I know that it easily sounds like I would think that. Changes in the amount of time someone can spend on a project like this just doesn't stay the same forever. This is just about figuring out how we can best deal with this. :)

**Comment by klemens** [comment]
I think @mswart is fine with us merging new parsers and fixing existing ones (I've done so multiple times over that last year). I usually try to respond quickly to new pull requests, but I am currently working on my master thesis so I haven't had much time lately. I intend to invest more time once that is done (June/July). Then I will also come back to your pull request regarding regression testing.

**Comment by Y0hy0h** [comment]
There is also the other repos (for PyOpenMensa and OpenMensa) that have PRs that are untouched for months now. I just felt like here are more people to discuss this with. :)

Maybe a "democratic" approach like we have here might work. But I think then it might be helpful to have some guidelines on what to look for when merging new parser etc, since I personally am a bit unsure of how to judge PRs and existing parsers. What do you think of aggregating rules/things to look for in a guideline document?

**Comment by Y0hy0h** [comment]
There is also the issue of diffusion of responsibility. Since I'm unsure of how to deal with issues/PRs, and I'm not the only one with merge rights, I just lay back and let you guys deal with it. :)

Having some "roles" helps with this, since I know who to ping/ask/replace for a given task.

**Comment by klemens** [comment]
> since I personally am a bit unsure of how to judge PRs and existing parsers

I just reviewed the saarland parser pull request, if you would like some inspiration :wink:. I generally go through the code line by line and have the source (api or website) and the generated xml open for reference. This way I "manually" parse the source in my head. If something is unclear or wrong, I add a comment. I also usually make some general notes separately, that get condensed into one or more comments at the end. Sometimes I play around with the code a little bit to test robustness and edge cases.

> Having some "roles" helps with this, since I know who to ping/ask/replace for a given task.

I am not sure if we need roles, but feel free to ping me directly if you are unsure about anything.

**Comment by Y0hy0h** [comment]
Thanks, I will try to have a look at it later on. ;)

Is there a way to send you a PM? If not, maybe it's a good idea to start a Discord or similar channel for quick and dirty communication and questions?

**Comment by klemens** [comment]
> Is there a way to send you a PM?

Just send me an email (address is on my profile). :wink:

**Comment by Y0hy0h** [comment]
Ok. :D So easy.

What do think of a Discord/Gitter, though?

**Comment by klemens** [comment]
FYI: #89

**Comment by Y0hy0h** [comment]
@klemens, I don't know where else to write this:
Thanks a lot for taking charge of the parsers! It's really nice of you to not only host then but also have the initiative to propose that.

Thank you!

**Comment by klemens** [comment]
I am going to close this. The most realistic path forward is probably moving the parsers and the python lib into the openmensa org, but like mentioned in another thread, I currently don't have time for that.
