### ISSUE TITLE
wrong mensa name muenchen/archisstrasse

### ISSUE THREAD

**Issue by Supersonic112** [mswart/openmensa-parsers#93]
Tiny spelling error:
https://github.com/mswart/openmensa-parsers/blob/dbdea4d255457a5f9db091b42597d0b9ad415b06/parsers/muenchen.py#L117
The name should be arcisstrasse instead of arc**h**isstrasse, see also [OpenStreetMap](https://www.openstreetmap.org/way/19183732#map=19/48.14727/11.56724).

I can create a PR if you want, but most likely its faster if you just remove the 'h' directly.

**Comment by klemens** [comment]
Thanks for the note, however the name of the [canteen on openmensa.org](https://openmensa.org/c/138) is at least correct.

I cannot fix this currently, as I would also need to change it at opemnesa.org, but I don't have access to the munich parser. @mswart would probably need to do this, but he hasn't been active lately.
