### ISSUE TITLE
Update Rostock Mensas

### ISSUE THREAD

**Issue by Matthias84** [mswart/openmensa-parsers#98]
Hi,

here at Rostock are some updates nesssary:
* new Mensa Ulme - [Ulmenstraße 69, Haus 5](https://www.openstreetmap.org/note/1761025#map=19/54.08539/12.10928), `mensa_id_3`
* Mensa Kleine Ulme closed
* Mensa Ulme 69 will be closed after tomorrow

**Comment by klemens** [comment]
So kleine Ulme (was previously id 3) is now just Ulme? I'll update in a moment!

**Comment by klemens** [comment]
There also seems to be the canteen Kantilene which is not yet included.

**Comment by klemens** [comment]
Quick summary of changes:
* Kleine Ulme is now called just [Ulme](https://openmensa.org/c/372) (reused the id on openmensa.org, so it stays in favorites etc.)
* [Ulme 69](https://openmensa.org/c/373) is now disabled
* Added [Kantilene](https://openmensa.org/c/879)
* Renamed Cafeteria Einstein to [Mensa E1nstein](https://openmensa.org/c/369)
* Fixed [St.-Georg-Straße](https://openmensa.org/c/370) (the ß in the parser name was causing problems)
* The parser is now running on omfeeds.crpt.de
