### ISSUE TITLE
Parser for Ostniedersachsen is outdated

### ISSUE THREAD

**Issue by BrainConverter** [mswart/openmensa-parsers#99]
The STW-ON has a new website which makes the [parser](https://github.com/mswart/openmensa-parsers/blob/master/parsers/ostniedersachsen.py) outdated!

Old page: https://www.stw-on.de/wolfenbuettel/essen/menus/mensa-ostfalia
New page: https://www.stw-on.de/wolfenbuettel/essen/mensa/

**Comment by klemens** [comment]
Thanks for the report, I will have a look tomorrow!

**Comment by klemens** [comment]
I have started working on a new parser based on the new API: #100 However, it is not finished yet.

**Comment by BrainConverter** [comment]
Is there any documentation for their API? (http://api.stw-on.de)

**Comment by klemens** [comment]
I have finished the parser, will now update the openmensa.org website!

> Is there any documentation for their API? (http://api.stw-on.de)

I haven't found any, I just got a short message that I should use the API when fetching the homepage using a non-browser user agent, but it seems that it no longer the case (I cannot reproduce it now)?

**Comment by klemens** [comment]
I have updated the website. All canteens work again and there are also four new ones that were missing until now:

* [Cafeteria Mensa 2](https://openmensa.org/c/903)
* [Bistro NFF](https://openmensa.org/c/895)
* [Mensa Salzgitter](https://openmensa.org/c/898)
* [Bistro Wolfsburg](https://openmensa.org/c/900)
